- id: doi:10.1101/2022.01.26.477748
  date: 2022-1-31
  extra-links:
    - type: preprint
      link: https://doi.org/10.1101/2022.01.26.477748
  tags:
    - spatial transcriptomics 

- id: doi.org/10.1242/dev.199616
  image: https://cob.silverchair-cdn.com/cob/content_public/journal/dev/issue/148/18/40/develop_148_18.coverfig.png?Expires=1652306391&Signature=idi2vB8R6E6LoLiPaUZ5jj9nJwZ4LVHjVbvSzyuYPz~ZshAoJtEbpuoj1XLQNIvm202rWA7hseBc6uXFdHK~FUVddHVmTV963Qcn2LDG~vL-zMTxAN9rrU3o8RKFI21FDEdylc2iy0O37GiPtMnL97Z1T-FXUtT-zPXK7LQ-EaZZyVhD3I6i6sip77AtI9Z25GI~Q-dCCpxjty6xuh~mqEgGPHZ4oTgkEp-nBquGHAQbCQ~2p556lrRZpaQY9GJWeeG-XlLow~XgEaxdsEsq0uysRlooTR-lOtzfZb~QK0fA93258JdQ8zBLB-TEhPOB5akAmHqRErPfxA7TEe4DyA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
    - imaging
    - developmental biology
    - machine learning

#- id: doi:10.1016/j.csbj.2020.05.017
#  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg
#  date: 2020-6-2
#  extra-links:
#    - type: manubot
#      link: https://greenelab.github.io/knowledge-graph-review/
#  tags:
#    - knowledge graphs

#- id: doi:10.1371/journal.pcbi.1007128
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  repo: greenelab/meta-review
#  extra-links:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/

#- id: doi:10.7554/eLife.32822
#  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
#  extra-links:
#    - type: preprint
#      link: https://doi.org/10.7287/peerj.preprints.3100v1
#    - type: manubot
#      link: https://greenelab.github.io/scihub-manuscript/
#    - type: source
#      link: https://github.com/greenelab/scihub-manuscript
#      text: Manuscript source
#    - type: source
#      link: https://github.com/greenelab/scihub
#      text: Analyses source
